#!/bin/bash

home_dir="/Users/riadas/Documents/phd/classes/databases/final_project/PClean"
# home_dir="/afs/csail.mit.edu/u/r/riadas/phd/PClean"
methods=("synthesis_from_jsons") # ("synthesis_from_jsons" "direct_synthesis")
benchmarks=("rents")
counter=0
for method in ${methods[@]}
do 
    for benchmark in ${benchmarks[@]}; 
    do
        for filename in "$home_dir/multiple_hypotheses_base/hypotheses_copy/$method/$benchmark"/*
        do
            echo "julia --project=$home_dir $home_dir/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl $method $benchmark $filename"
            # sleep 10
        done
    done
    # sleep 32400
done

# /scratch/riadas/julia-1.9.4/bin/julia --project=/afs/csail.mit.edu/u/r/riadas/phd/PClean /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format1_base1_0.jl
# /scratch/riadas/julia-1.9.4/bin/julia --project=/afs/csail.mit.edu/u/r/riadas/phd/PClean /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format1_base1_1.jl
# /scratch/riadas/julia-1.9.4/bin/julia --project=/afs/csail.mit.edu/u/r/riadas/phd/PClean /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format1_base1_2.jl
# /scratch/riadas/julia-1.9.4/bin/julia --project=/afs/csail.mit.edu/u/r/riadas/phd/PClean /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format1_base1_3.jl
# /scratch/riadas/julia-1.9.4/bin/julia --project=/afs/csail.mit.edu/u/r/riadas/phd/PClean /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format1_base1_4.jl
# /scratch/riadas/julia-1.9.4/bin/julia --project=/afs/csail.mit.edu/u/r/riadas/phd/PClean /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format1_base1_5.jl
# /scratch/riadas/julia-1.9.4/bin/julia --project=/afs/csail.mit.edu/u/r/riadas/phd/PClean /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format1_base1_6.jl
# /scratch/riadas/julia-1.9.4/bin/julia --project=/afs/csail.mit.edu/u/r/riadas/phd/PClean /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format1_base1_7.jl
# /scratch/riadas/julia-1.9.4/bin/julia --project=/afs/csail.mit.edu/u/r/riadas/phd/PClean /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format1_original.jl
# /scratch/riadas/julia-1.9.4/bin/julia --project=/afs/csail.mit.edu/u/r/riadas/phd/PClean /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format2_base1_0.jl
# /scratch/riadas/julia-1.9.4/bin/julia --project=/afs/csail.mit.edu/u/r/riadas/phd/PClean /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format2_base1_1.jl
# /scratch/riadas/julia-1.9.4/bin/julia --project=/afs/csail.mit.edu/u/r/riadas/phd/PClean /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format2_base1_2.jl
# /scratch/riadas/julia-1.9.4/bin/julia --project=/afs/csail.mit.edu/u/r/riadas/phd/PClean /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format2_base1_3.jl
# /scratch/riadas/julia-1.9.4/bin/julia --project=/afs/csail.mit.edu/u/r/riadas/phd/PClean /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format2_base1_4.jl
# /scratch/riadas/julia-1.9.4/bin/julia --project=/afs/csail.mit.edu/u/r/riadas/phd/PClean /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format2_base1_5.jl
# /scratch/riadas/julia-1.9.4/bin/julia --project=/afs/csail.mit.edu/u/r/riadas/phd/PClean /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format2_base1_6.jl
# /scratch/riadas/julia-1.9.4/bin/julia --project=/afs/csail.mit.edu/u/r/riadas/phd/PClean /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format2_base1_7.jl
/scratch/riadas/julia-1.9.4/bin/julia --project=/afs/csail.mit.edu/u/r/riadas/phd/PClean /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /afs/csail.mit.edu/u/r/riadas/phd/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format2_original.jl

julia --project=/Users/riadas/Documents/phd/classes/databases/final_project/PClean /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format1_base1_0.jl
julia --project=/Users/riadas/Documents/phd/classes/databases/final_project/PClean /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format1_base1_1.jl
julia --project=/Users/riadas/Documents/phd/classes/databases/final_project/PClean /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format1_base1_2.jl
julia --project=/Users/riadas/Documents/phd/classes/databases/final_project/PClean /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format1_base1_3.jl
julia --project=/Users/riadas/Documents/phd/classes/databases/final_project/PClean /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format1_base1_4.jl
julia --project=/Users/riadas/Documents/phd/classes/databases/final_project/PClean /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format1_base1_5.jl
julia --project=/Users/riadas/Documents/phd/classes/databases/final_project/PClean /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format1_base1_6.jl
julia --project=/Users/riadas/Documents/phd/classes/databases/final_project/PClean /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format1_base1_7.jl
julia --project=/Users/riadas/Documents/phd/classes/databases/final_project/PClean /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format1_original.jl
julia --project=/Users/riadas/Documents/phd/classes/databases/final_project/PClean /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format2_base1_0.jl
julia --project=/Users/riadas/Documents/phd/classes/databases/final_project/PClean /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format2_base1_1.jl
julia --project=/Users/riadas/Documents/phd/classes/databases/final_project/PClean /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format2_base1_2.jl
julia --project=/Users/riadas/Documents/phd/classes/databases/final_project/PClean /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format2_base1_3.jl
julia --project=/Users/riadas/Documents/phd/classes/databases/final_project/PClean /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format2_base1_4.jl
julia --project=/Users/riadas/Documents/phd/classes/databases/final_project/PClean /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format2_base1_5.jl
julia --project=/Users/riadas/Documents/phd/classes/databases/final_project/PClean /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format2_base1_6.jl
julia --project=/Users/riadas/Documents/phd/classes/databases/final_project/PClean /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format2_base1_7.jl
julia --project=/Users/riadas/Documents/phd/classes/databases/final_project/PClean /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format2_original.jl
(base) Rias-MacBook-Pro:PClean riadas$ 00~julia --project=/Users/riadas/Documents/phd/classes/databases/final_project/PClean /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/scripts/compute_best_overall_program_rents.jl synthesis_from_jsons rents /Users/riadas/Documents/phd/classes/databases/final_project/PClean/multiple_hypotheses_base/hypotheses_copy/synthesis_from_jsons/rents/format1_base1_0.jl